# -*- coding: utf-8 -*-
"""
/***************************************************************************
 opeNoise

 opeNoise allows to compute the noise level generated by point source or 
 by road source at fixed receiver points and buildings.

                             -------------------
        begin                : March 2014
        copyright            : (C) 2014 by Arpa Piemonte
        email                : s.masera@arpa.piemonte.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from __future__ import absolute_import
import os, site, sys

if site.USER_SITE not in sys.path:
    sys.path.append(site.USER_SITE)

from .utils import ensure_pyjnius, ensure_jdk, ensure_noisemodelling
if not ensure_jdk():
    raise Exception("Plugin initialisation failed because the java jdk could not be properly installed")
if not ensure_noisemodelling():
    raise Exception("Plugin initialisation failed because the noisemodelling libs could not be properly installed")
if not ensure_pyjnius():
    raise Exception("Plugin initialisation failed because the pyjnius dependency could not be installed")

def classFactory(iface):
    # load opeNoise class from file opeNoise
    from .opeNoise import opeNoise
    return opeNoise(iface)
